spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${daehanl8635@gmail.com} # 앱 비밀번호를 발급받은 구글 계정
    password: ${ofamphhcauxofsey} # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true